//组件属性
const list = [
  {
    component: 'u-text',
    label: '文本',
    propValue: '文本',
    icon: 'el-icon-edit',
    locked: false,
    style: {
      width: 200,
      height: 100,
      left: 0,
      top: 0,
      fontSize: 14,
      fontWeight: 500,
      color: '#000',
      lineHeight: 33,
      textAlign: 'left',
      alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#000',
      textDecoration: 'none',
      fontStyle: 'normal',
      borderStyle: "solid solid solid solid",
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
      borderBottomLeftRadius: 0,

    },
  },
  {
    component: "u-picture",
    label: "图片",
    icon: 'el-icon-picture',
    locked: false,
    images: [require("@/assets/1.jpg"), require("@/assets/2.jpg"),
    require("@/assets/3.jpg")],//实际组件是动态绑定src的，需要先引入
    auto: true,
    autoTime: 2,
    style: {
      width: 200,
      height: 200,
      left: 0,
      top: 0,
    },
  },
  {
    component: "u-button",
    label: "按钮",
    propValue: '按钮',
    icon: 'el-icon-thumb',
    events: {},
    locked: false,//是否锁定编辑
    style: {
      width: 200,
      height: 60,
      left: 0,
      top: 0,
      fontSize: 14,
      fontWeight: 500,
      color: '#000',
      lineHeight: 33,
      textAlign: 'center',
      alignItems: 'flex-start',
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#000',
      textDecoration: 'none',
      fontStyle: 'normal',
      borderStyle: "solid solid solid solid",
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
      borderBottomLeftRadius: 0,
    }
  }
];
export default list
